### ISSUE TITLE
How can i make section header sticky to top on scrolling recyclerview ? 

### ISSUE THREAD

**Issue by developerShubhamAgr** [zhukic/Sectioned-RecyclerView#16]
Hello ,
I would like to thankyou for the amazing library that you have made.

But i was wondering if we can make section header's sticky to the top ?
Is there any methods or tricks for sticky sectioned header's?.

Thankyou.

**Comment by zhukic** [comment]
Hi @developerShubhamAgr. Currently, there is no possibility to make section header sticky. And I'm not sure that this feature will be added in the near future.

**Comment by developerShubhamAgr** [comment]
@zhukic  Thankyou anyways.
