### ISSUE TITLE
USING LIBRARY WITH NEW PAGING LIBRARY FROM ARCHITECTURE COMPONENTS OR WITH DIFFUTILS

### ISSUE THREAD

**Issue by aliumujib** [zhukic/Sectioned-RecyclerView#17]
Hello @zhukic,

Great library, I love using it. I am trying to implement an app that uses this library for a sectioned list of notifications. I would love to use it with the PagedListAdapter from android architecture components but I think that's a tall order. So is there a way I can at least use the library with DiffUtils?

Regards,
Mujib.

**Comment by zhukic** [comment]
Hi @aliumujib. 
Sorry for late reply. Currently there is no possibility to use this library in conjunction with DiffUtil because default DiffUtil implementation calls ```notifyItemRangeInserted```, ```notifyItemRangeRemoved```, ```notifyItemRangeChanged``` methods which current library doesn't yet support. This feature will be added in the next releases.

**Comment by hivian** [comment]
This feature would be helpful, in order not to create a new SectionedListAdapter instance each time I want to insert new data in it.

**Comment by zhukic** [comment]
Hi, @hivian. 
Currently, I'm not planning to add Paging Library in the nearest future. Sorry for that.
