### ISSUE TITLE
Is it possible to getFooterViewHolder?

### ISSUE THREAD

**Issue by douglasalipio** [zhukic/Sectioned-RecyclerView#21]
Hi,

As the zhukic/sectioned-recyclerView is a fork of luizgrp/sectioned-recylcerAdapter in luizgrp lib is possible to have a footer view so can I use that behaviour in zhukic library? 

Thanks,
:D

**Comment by zhukic** [comment]
Hi, @douglasalipio. Sorry, but this library is not a fork of [luizgrp/sectioned-recylcerAdapter](https://github.com/luizgrp/SectionedRecyclerViewAdapter), and, unfortunately, this library doesn't support fotters.

Sorry for that. :smiley:

**Comment by douglasalipio** [comment]
@zhukic My bad :dango: Thanks for you replayed me.
