### ISSUE TITLE
Expand not working correctly. Section header is pushed inside other section

### ISSUE THREAD

**Issue by JibuVarghese** [zhukic/Sectioned-RecyclerView#29]
Hi Sir ,
Issue scenario : All sections are in collapsed state and I expand a section and after that when I am expanding all sections using adapter.expandAllSections(); when user click on a button. Already expanded section header is pushed inside the top section header.

Please suggest me a workaround to handle this.

**Comment by zhukic** [comment]
Hi, @JibuVarghese. Sorry for late reply.
Is it possible to create a sample project which demonstrates this issue, because it's difficult to figure out where problem is?

**Comment by JibuVarghese** [comment]
Hi Sir, same issue is there in your sample app "Movies". Can I send screenshot of the issue to your mail id?

**Comment by zhukic** [comment]
@JibuVarghese sure.

**Comment by kathir-t** [comment]
@zhukic Hi! May I know how to fix this?

**Comment by zhukic** [comment]
@JibuVarghese I've reproduced the issue and fixed it. 
Please try out 1.2.2 version or the library. It's also available on Google Play.

Thanks a lot for your contibution.

**Comment by JibuVarghese** [comment]
@zhukic Hi Sir, i checked your demo app in google play. it is working fine now as per the required way.
thank you for the new update. appreciate it.
