### ISSUE TITLE
How can I remove the subheader over the first element?

### ISSUE THREAD

**Issue by UltraNeon** [zhukic/Sectioned-RecyclerView#31]
How can I remove the subheader over the first element?
`if (position == 0)`  removes the subheader between the first and second elements, and the subheader over the first element remains

**Comment by zhukic** [comment]
Maybe this issue https://github.com/zhukic/Sectioned-RecyclerView/issues/11 will help you.

**Comment by UltraNeon** [comment]
Thanks!
