### ISSUE TITLE
onbindviewholder is called when list is empty

### ISSUE THREAD

**Issue by yosemiteyss** [zhukic/Sectioned-RecyclerView#33]
When I implement filterable and got an empty arraylist, onbindviewholder/onplacesubheaderbetweenitems are called, providing position 0 (causing indexoutofbound). It didn't happen in the default adapter. How can I solve this?

**Comment by zhukic** [comment]
@hctibs678  Can you create some sample app which demonstrates the issue? Because I can't recommend anything because I don't know where the bug is.

**Comment by yosemiteyss** [comment]
@zhukic I have created a sample app demonstrating the problem. 
https://github.com/hctibs678/testproject

**Comment by zhukic** [comment]
@hctibs678 You need to call ```notifyDataChanged``` method instead of ```notifyDataSetChanged```.
It is required to recalculate the state of sections.

**Comment by yosemiteyss** [comment]
@zhukic After using `notifyDataChanged`, everything work fine. Thanks a lot for helping!
