### ISSUE TITLE
Building a sectioned HORIZONTAL recyclerview in android

### ISSUE THREAD

**Issue by SAGARSURI** [zhukic/Sectioned-RecyclerView#34]
Is it possible to build such layout with this?

<img width="681" alt="Screenshot 2019-06-19 at 6 36 53 PM" src="https://user-images.githubusercontent.com/14856659/59770407-99ea6a00-92c5-11e9-8808-fb6fc7961372.png">

<img width="271" alt="Screenshot 2019-06-19 at 6 39 23 PM" src="https://user-images.githubusercontent.com/14856659/59770437-aa024980-92c5-11e9-9140-02add78d78d5.png">

<img width="252" alt="Screenshot 2019-06-19 at 6 40 24 PM" src="https://user-images.githubusercontent.com/14856659/59770451-b1c1ee00-92c5-11e9-8a45-f0f2e09e2f5e.png">

**Comment by zhukic** [comment]
@SAGARSURI, I'm not sure.
